### ISSUE TITLE
recipes Precision cutting augment

### ISSUE THREAD

**Issue by Zlovono** [CraftYourTown/cyt-wiki#19]
1x Anvil
1x Diamond Sword
1x Iron Sword
16x Cobblestone
2x Emerald
3x Lapis Block
1x Water Bucket
1x Wither Skeleton Skull
6x Nautilus Shell

**1x Iron Sword should be 1x Iron Axe**

**Comment by lukemango** [comment]
fixed in https://github.com/CraftYourTown/cyt-wiki/commit/b627f3b0e2048d104e59627fea31f21b12e9185c
