### ISSUE TITLE
essence information is wrong (towny)

### ISSUE THREAD

**Issue by Abomination711** [CraftYourTown/cyt-wiki#23]
In the wiki under towny mob spawners, it talks about getting all spawners and fuel from /warp trader (which does not exist on towny) i think the information on the fuel types and the spawners themselves are correct, but the way to get them is not.

**Comment by Oribuin** [comment]
Fixed in #22

**Comment by Oribuin** [comment]
oops lmfao

**Comment by lukemango** [comment]
No longer relevant for V11
